#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 

bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false

bspc config border_width        1 
bspc config window_gap          3
bspc config focused_border_color "#cc241d" #"#6454A1"
bspc config normal_border_color "#8ec07c" #"#323248"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config bottom_padding 41

# bspc rule -a qutebrowser desktop='^2' follow=on
# bspc rule -a Zathura state=tiled
# bspc rule -a Screenkey manage=off
bspc rule -a plasmashell manage=off
